nifty_50 = [
    "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK",
    "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BEL", "BHARTIARTL",
    "CIPLA", "COALINDIA", "DRREDDY", "EICHERMOT", "ETERNAL",
    "GRASIM", "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO",
    "HINDALCO", "HINDUNILVR", "ICICIBANK", "ITC", "INDUSINDBK",
    "INFY", "JSWSTEEL", "JIOFIN", "KOTAKBANK", "LT",
    "M&M", "MARUTI", "NTPC", "NESTLEIND", "ONGC",
    "POWERGRID", "RELIANCE", "SBILIFE", "SHRIRAMFIN", "SBIN",
    "SUNPHARMA", "TCS", "TATACONSUM", "TATAMOTORS", "TATASTEEL",
    "TECHM", "TITAN", "TRENT", "ULTRACEMCO", "WIPRO"
]

nifty_50_by_sector = {
    'IT': ["INFY","TCS","HCLTECH","TECHM","WIPRO"],
    "Banking": ["HDFCBANK","ICICIBANK","KOTAKBANK","SBIN","AXISBANK"],
    "Finance": ["BAJFINANCE","BAJAJFINSV","SHRIRAMFIN","HDFCLIFE","SBILIFE","JIOFIN"],
    'Automobile': ["BAJAJ-AUTO","HEROMOTOCO","M&M","MARUTI","TATAMOTORS","EICHERMOT"],
    'Energy': ["RELIANCE","ONGC","POWERGRID","COALINDIA","NTPC"],
    'Metals': ["TATASTEEL","JSWSTEEL","HINDALCO"],
    'Pharma': ["APOLLOHOSP","CIPLA","DRREDDY","SUNPHARMA"],
    'FMCG': ["HINDUNILVR","ITC","NESTLEIND","TATACONSUM"],
    'Consumer_Durables': ["ASIANPAINT","TITAN"],
    'Retail': ["TRENT","ETERNAL"],
    'Telecom': ["BHARTIARTL"],
    'Defence': ["BEL","LT"],
    'Construction': ["GRASIM","ULTRACEMCO"],
    'Services_Infrastructure': ["ADANIPORTS"]
}