"""add category column in transaction table

Revision ID: 124458b77fc9
Revises: 
Create Date: 2026-07-17 19:22:25.743439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124458b77fc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Use direct add_column statements instead of the buggy batch_op block
    op.add_column('transaction', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('transaction', sa.Column('wallet_ref', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'wallet_ref')
    op.drop_column('transaction', 'category')    # ### end Alembic commands ###
