"""add children column in UserAditionalInfo table

Revision ID: 1392e4498522
Revises: ac359e5ffc1a
Create Date: 2026-07-30 15:51:37.609564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1392e4498522'
down_revision = 'ac359e5ffc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
