"""add langitude column in transaction table

Revision ID: 152199ed6bc8
Revises: 37b360a61501
Create Date: 2026-07-28 16:50:28.556171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152199ed6bc8'
down_revision = '37b360a61501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('transaction', schema=None) as batch_op:
       #  batch_op.add_column(sa.Column('langitude', sa.Float(), nullable=True))
       pass
       #  batch_op.alter_column('category',
       #         existing_type=sa.VARCHAR(length=100),
       #         nullable=False)
       #  batch_op.alter_column('wallet_ref',
       #         existing_type=sa.VARCHAR(length=100),
       #         nullable=False)
       #  batch_op.create_unique_constraint(None, ['wallet_ref'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
        pass
    # ### end Alembic commands ###
