"""drop user_wallet column from user table

Revision ID: 2ceeb666bae0
Revises: 1392e4498522
Create Date: 2026-08-13 16:08:33.106129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ceeb666bae0'
down_revision = '1392e4498522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('app_password',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('wallet_ref')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_ref', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('app_password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
