"""Added app_password column from Account table

Revision ID: 403398bba7ca
Revises: 5a49f7e31d5a
Create Date: 2026-08-17 11:57:23.528347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403398bba7ca'
down_revision = '5a49f7e31d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('app_password')

    # ### end Alembic commands ###
