"""add gender column in UserAditionalInfo table

Revision ID: 4f1a41037996
Revises: d13df8f19174
Create Date: 2026-07-30 14:22:18.086494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1a41037996'
down_revision = 'd13df8f19174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
