"""drop app_password column from Account table

Revision ID: 5a49f7e31d5a
Revises: 5d13680b90ef
Create Date: 2026-08-17 11:54:13.475936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a49f7e31d5a'
down_revision = '5d13680b90ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('app_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_password', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
