"""added invest_type column in dematholdings table

Revision ID: 5d13680b90ef
Revises: 52e15cbb0f09
Create Date: 2026-08-14 16:10:47.955916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d13680b90ef'
down_revision = '52e15cbb0f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demat_holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invest_type', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demat_holdings', schema=None) as batch_op:
        batch_op.drop_column('invest_type')

    # ### end Alembic commands ###
