"""add family_type column in UserAditionalInfo table

Revision ID: 84e9ec0e2515
Revises: 4f1a41037996
Create Date: 2026-07-30 15:36:18.187384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e9ec0e2515'
down_revision = '4f1a41037996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass    
    # ### end Alembic commands ###
