"""add wallet_ref column in transaction table

Revision ID: 948fa3e72f2f
Revises: 124458b77fc9
Create Date: 2026-07-17 19:37:05.500928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948fa3e72f2f'
down_revision = '124458b77fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Use direct add_column statements instead of the buggy batch_op block
    pass
    # op.add_column('transaction', sa.Column('wallet_ref', sa.String(length=100), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('transaction', 'wallet_ref')
    pass
    # ### end Alembic commands ###
