"""add maritial_status column in UserAditionalInfo table

Revision ID: ac359e5ffc1a
Revises: f3abac6b1296
Create Date: 2026-07-30 15:46:41.850586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac359e5ffc1a'
down_revision = 'f3abac6b1296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
