"""add bank_approval column in demataccount table

Revision ID: b05c20a674e8
Revises: 948fa3e72f2f
Create Date: 2026-07-21 16:11:42.339434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05c20a674e8'
down_revision = '948fa3e72f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('demat_account', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('bank_approval', sa.String(length=100), nullable=False))
    pass

    # with op.batch_alter_table('transaction', schema=None) as batch_op:
    #     batch_op.alter_column('category',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=False)
    #     batch_op.alter_column('wallet_ref',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=False)
    #     batch_op.create_unique_constraint(None, ['wallet_ref'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('transaction', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='unique')
    #     batch_op.alter_column('wallet_ref',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=True)
    #     batch_op.alter_column('category',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=True)

    # with op.batch_alter_table('demat_account', schema=None) as batch_op:
    #     batch_op.drop_column('bank_approval')
    pass

    # ### end Alembic commands ###
