"""add dem_account_id column in demataccount table

Revision ID: ca832b404392
Revises: b05c20a674e8
Create Date: 2026-07-21 16:21:03.788920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca832b404392'
down_revision = 'b05c20a674e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('demat_account', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('dem_account_id', sa.Integer(), nullable=False))

    # with op.batch_alter_table('transaction', schema=None) as batch_op:
    #     batch_op.alter_column('category',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=False)
    #     batch_op.alter_column('wallet_ref',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=False)
    #     batch_op.create_unique_constraint(None, ['wallet_ref'])
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('transaction', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='unique')
    #     batch_op.alter_column('wallet_ref',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=True)
    #     batch_op.alter_column('category',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=True)

    # with op.batch_alter_table('demat_account', schema=None) as batch_op:
    #     batch_op.drop_column('dem_account_id')
    pass
    # ### end Alembic commands ###
