"""add longitude column in transaction table

Revision ID: cb6c46e57dc9
Revises: 152199ed6bc8
Create Date: 2026-07-28 16:58:35.418658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6c46e57dc9'
down_revision = '152199ed6bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
