"""add UserAditionalInfo model

Revision ID: d13df8f19174
Revises: cb6c46e57dc9
Create Date: 2026-07-28 17:04:30.319719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13df8f19174'
down_revision = 'cb6c46e57dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
