"""add blood_relation column in UserAditionalInfo table

Revision ID: f3abac6b1296
Revises: 84e9ec0e2515
Create Date: 2026-07-30 15:40:59.836463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3abac6b1296'
down_revision = '84e9ec0e2515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
